name: Publish Python Package to PyPi

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action  # Call the reusable setup step.

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Publish Package
        run: uv publish --trusted-publishing always
