name: Publish Python Package to PyPi

on:
  push:
    branches:
      - ci-cd
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.12

      - name: Build package
        run: uv build

      - name: Publish Package
        run: uv publish