name: Ruff

# Trigger this workflow on pull requests to ensure tests are executed before merging.
on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for compatibility and performance.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures the repository code is available.

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action  # Call the reusable setup step.

      - name: Run Ruff Linting
        run: uv run ruff check .