name: Ruff

# Trigger this workflow on pull requests to ensure tests are executed before merging.
on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for compatibility and performance.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures the repository code is available.

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action  # Call the reusable setup step.

      - name: Run Ruff Linting
        run: ruff check .

      - name: Upload Ruff Logs
        if: failure()  # Only upload logs if the step fails.
        uses: actions/upload-artifact@v4
        with:
          name: ruff-report
          path: ruff-report.txt